test:
  omniauth_provider:   :developer
  host:                tester.example.com
  searchable_provider: false
  smtp_address:        mailhost.example.com
  smtp_domain:         example.com
  support_mail:        supportoweb@example.com
  logout_link:         https://idptest.example.com/adfs/ls/?wa=wsignout1.0

